# Generated by Django 5.1 on 2024-08-29 04:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_rename_clients_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='amount',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='client',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2024, 8, 29, 7, 48, 19, 706508)),
        ),
        migrations.AddField(
            model_name='client',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 29, 7, 48, 19, 706508)),
        ),
    ]
