# Generated by Django 5.1 on 2024-08-29 06:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_client_amount_client_end_date_client_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='end_date',
            field=models.DateField(default=datetime.date(2024, 8, 29)),
        ),
        migrations.AlterField(
            model_name='client',
            name='start_date',
            field=models.DateTimeField(default=datetime.date(2024, 8, 29)),
        ),
    ]
