# Generated by Django 5.1 on 2024-08-29 09:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_client_end_date_alter_client_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='renewal_date',
            field=models.DateField(default=datetime.date(2024, 8, 29)),
        ),
        migrations.AlterField(
            model_name='client',
            name='start_date',
            field=models.DateField(default=datetime.date(2024, 8, 29)),
        ),
    ]
