# Generated by Django 5.1 on 2024-08-29 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_client_renewal_date_alter_client_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='renewal_date',
            field=models.DateField(),
        ),
    ]
