# Generated by Django 5.1 on 2024-08-29 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_alter_client_renewal_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='amount',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
