# Generated by Django 5.1 on 2024-08-30 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_alter_client_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='client',
            name='start_date',
            field=models.DateField(),
        ),
    ]
