# Generated by Django 5.1 on 2024-08-30 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_alter_client_end_date_alter_client_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='renewal_date',
            field=models.DateField(null=True),
        ),
    ]
