# Generated by Django 5.1 on 2024-08-30 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_alter_client_renewal_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
